[Icon Theme]
Name=Spaced Linux Dark folder icons
Comment=Spaced Linux Dark folder color over Papirus Dark
Inherits=Spaced-Menu-On-Dark,Papirus-Dark,hicolor
Directories=scalable/places,scalable/status,scalable/devices,scalable/apps,scalable/mimetypes

[scalable/places]
Size=64
Context=Places
Type=Scalable
MinSize=16
MaxSize=256

[scalable/status]
Size=48
Context=Status
Type=Scalable
MinSize=16
MaxSize=256

[scalable/devices]
Size=64
Context=Devices
Type=Scalable
MinSize=16
MaxSize=256

[scalable/apps]
Size=64
Context=Applications
Type=Scalable
MinSize=16
MaxSize=256

[scalable/mimetypes]
Size=48
Context=MimeTypes
Type=Scalable
MinSize=16
MaxSize=256
