dontChroot: false
timeout: 300
script:
  - "find /etc/skel -type d -exec chmod 0755 {} +"
  - "find /etc/skel -type f -exec chmod u+rw,go+r {} +"
  - "update-rc.d chrony defaults || true"
  - "update-rc.d chrony enable || true"
  - "chronyd -q 'pool pool.ntp.org iburst' || true"
  - "hwclock --systohc --utc || true"
  - "update-grub || true"
  - "update-initramfs -u -k all || true"
