#!/bin/bash

keyring=${SPACED_DEVUAN_KEYRING:-/usr/share/keyrings/devuan-archive-keyring.pgp}
[[ -r "$keyring" ]] || { echo "Missing Devuan archive key: $keyring" >&2; exit 1; }

lb config noauto \
    --distribution ceres \
    --archive-areas "main contrib non-free non-free-firmware" \
    --debian-installer none \
    --bootappend-live "boot=live components quiet loglevel=3 vt.global_cursor_default=0 username=user hostname=spaced" \
    --binary-image iso-hybrid \
    --iso-application "Spaced Linux 9.26.1" \
    --iso-preparer "Spaced Linux Team" \
    --iso-publisher "Spaced Linux" \
    --iso-volume "SpacedLinux926" \
    --linux-flavours amd64 \
    --linux-packages linux-image \
    --memtest none \
    --mirror-bootstrap "http://mirror.hootsoftware.com/devuan/merged" \
    --mirror-chroot "http://mirror.hootsoftware.com/devuan/merged" \
    --mirror-binary "http://mirror.hootsoftware.com/devuan/merged" \
    --parent-distribution ceres \
    --parent-mirror-bootstrap "http://mirror.hootsoftware.com/devuan/merged" \
    --parent-mirror-chroot "http://mirror.hootsoftware.com/devuan/merged" \
    --parent-mirror-binary "http://mirror.hootsoftware.com/devuan/merged" \
    --security false \
    --updates false \
    --backports false \
    --firmware-binary false \
    --firmware-chroot false \
    --apt-indices false \
    --apt-source-archives false \
    --apt-recommends false \
    --apt-secure true \
    --cache true \
    --cache-indices false \
    --cache-packages true \
    --cache-stages bootstrap \
    --bootloaders "grub-pc grub-efi" \
    --initramfs live-boot \
    --initsystem sysvinit \
    --mode debian \
    --system live \
    --debootstrap-script sid \
    --verbose \
    --debootstrap-options "--keyring=$keyring --include=systemd-standalone-sysusers,systemd-standalone-tmpfiles --exclude=bootlogd,cron,cron-daemon-common,logrotate,dhcpcd-base,ifupdown"
