[greeter]
background=/usr/share/backgrounds/spaced/SimpleBackb.png
theme-name=Spaced-Dark
icon-theme-name=Papirus-Dark
user-background=false
default-user-image=/usr/share/icons/hicolor/256x256/apps/spaced-linux.png
logo=/usr/share/pixmaps/spaced-logo.png
indicators=~host;~spacer;~clock;~spacer;~session;~language;~a11y;~power
clock-format=%A, %B %d  %H:%M
