---
modules-search: [ local, /usr/lib/calamares/modules ]

instances:
  - id: spaced-time-sync
    module: shellprocess
    config: shellprocess@spaced-time-sync.conf

  - id: spaced-machineid
    module: shellprocess
    config: shellprocess@spaced-machineid.conf

  - id: spaced-postinstall
    module: shellprocess
    config: shellprocess@spaced-postinstall.conf

  - id: spaced-cleanup
    module: shellprocess
    config: shellprocess@spaced-cleanup.conf

oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
hide-back-and-next-during-exec: false
quit-at-end: false

sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - users
      - summary

  - exec:
      - shellprocess@spaced-time-sync
      - partition
      - mount
      - unpackfs
      - luksbootkeyfile
      - dpkg-unsafe-io
      - shellprocess@spaced-machineid
      - fstab
      - locale
      - keyboard
      - localecfg
      - users
      - displaymanager
      - networkcfg
      - hwclock
      - grubcfg
      - bootloader
      - packages
      - shellprocess@spaced-postinstall
      - shellprocess@spaced-cleanup
      - plymouthcfg
      - initramfscfg
      - initramfs
      - dpkg-unsafe-io-undo
      - umount

  - show:
      - finished

branding: spaced
prompt-install: false
dont-chroot: false
